#!/usr/bin/env python
#encoding=utf-8

# psr-reg-shuffle.py
# This file is part of PSR Registration Shuffler
#
# Copyright (C) 2008 - Dennis Schulmeister  <dennis -at- ncc-1701a.homelinux.net>
#
# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# It is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301  USA

'''
PURPOSE
=======

This script starts the system-wide installed version of the application.
'''

# Import global modules
import __builtin__
import sys
import os
import os.path


# Try to use local GTK library if present
# NOTE: This needs to be done prior to the first gtk import.
# NOTE: This only applies to the MS Windows distribution which comes with
# bundled GTK+ binaries. It doesn't affect other operating systems, though.
gtkLibPath = os.path.join(sys.prefix, "GTK", "lib")
if os.path.exists(gtkLibPath):
    os.environ["PATH"] = "%s;%s" % (gtkLibPath, os.environ["PATH"])

gtkBinPath = os.path.join(sys.prefix, "GTK", "bin")
if os.path.exists(gtkBinPath):
    os.environ["PATH"] = "%s;%s" % (gtkBinPath, os.environ["PATH"])


# Initialize l8n support
import psrregshuffle.translation

domainName = "psrregshuffle"
localeDir  = os.path.join(sys.prefix, "share", "locale")

psrregshuffle.translation.init(domainName, localeDir)


# Set path of data directory
import psrregshuffle.const

dataDir = os.path.join(sys.prefix, "share", psrregshuffle.const.techname)
__builtin__.__dict__["__PSR_DATA_DIR__"] = dataDir


# Start application
import psrregshuffle.main
app = psrregshuffle.main.Main.getInstance()
app.run()
